Bump golang.org/x/net to v0.56.0 for Go 1.27 compatibility
Build with Go 1.27rc1 fails:

$ go1.27rc1 build ./...
# google.golang.org/grpc/internal/transport
../../../go/pkg/mod/google.golang.org/grpc@v1.81.1/internal/transport/handler_server.go:271:18: undefined: http2.TrailerPrefix

Due to
* https://github.com/golang/go/issues/67810

See
* https://github.com/golang/go/discussions/60746

Bumped via
$ go get golang.org/x/net@v0.56.0 && go mod tidy
go: upgraded golang.org/x/crypto v0.51.0 => v0.53.0
go: upgraded golang.org/x/net v0.54.0 => v0.56.0
go: upgraded golang.org/x/sync v0.20.0 => v0.21.0
go: upgraded golang.org/x/sys v0.44.0 => v0.46.0
go: upgraded golang.org/x/text v0.37.0 => v0.38.0